# Generated by Django 3.0.6 on 2020-05-17 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20200517_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 18, 25, 36, 58951, tzinfo=utc)),
        ),
    ]
